import { useMemo, useState } from 'react';
import { BookOpen, Check, ChevronRight, CircleHelp, Dna, Download, Leaf, Menu, Moon, Search, Sparkles, Sun, X } from 'lucide-react';

const modules = [
  { id: 1, title: 'Клеткалык биология жана зат алмашуу', short: 'Клетка', icon: '◈', color: 'mint', topics: ['Тирүү организмдердин негизги касиеттери жана уюшулуу деңгээлдери', 'Клетка — тиричиликтин элементардык бирдиги', 'Клетканын химиялык курамы: Суу жана минералдык туздар', 'Органикалык заттар: Углеводдор жана Липиддер', 'Белоктор: Түзүлүшү жана функциялары', 'Нуклеин кислоталары: ДНК жана РНК', 'АТФ жана клеткадагы энергия', 'Цитоплазма жана органоиддор', 'Митохондриялар жана Пластидалар', 'Ядро жана хромосомалар', 'Метаболизм: Ассимиляция жана Диссимиляция', 'Фотосинтез жана Хемосинтез'], subs: ['Метаболизм, Дүүлүгүчтүк, Уюшулуунун 6 деңгээли', 'Клеткалык теориянын тарыхы, Прокариоттор vs Эукариоттор', 'Суунун биохимиялык касиети, Иондордун мааниси', 'Моносахариддер, Полисахариддер, Майлардын функциясы', 'Аминокислоталар, Белоктун 4 структурасы, Денатурация', 'ДНК кош спиралы, Комплементардуулук, РНК түрлөрү', 'АТФ макроэрг байланыштары, Клеткалык энергия аккумулятору', 'ЭПС, Гольджи комплекси, Лизосомалар', 'Клеткалык дем алуу, Хлоропласттардын түзүлүшү', 'Кариотип, Хроматин, ДНК сакталышы', 'Пластикалык жана Энергетикалык алмашуу этаптары', 'Жарык жана Караңгылык фазалары, Автотрофтор'] },
  { id: 2, title: 'Организмдердин көбөйүшү жана өрчүшү', short: 'Өрчүү', icon: '✦', color: 'lime', topics: ['Клетканын бөлүнүшү: Митоз', 'Мейоз бөлүнүшү', 'Жыныссыз көбөйүү', 'Жыныстык көбөйүү жана Гаметогенез', 'Уруктануу процесси', 'Онтогенез: Эмбрионалдык өрчүү', 'Постэмбрионалдык өрчүү', 'Сырткы чөйрөнүн түйүлдүккө таасири'], subs: ['Интерфаза, Митоздун 4 фазасы (Профаза, Метафаза, Анафаза, Телофаза)', 'Мейоз I жана Мейоз II, Кроссинговер, Жыныс клеткалары', 'Вегетативдик, Бүчүрлөнүү, Спора аркылуу көбөйүү', 'Сперматогенез, Оогенез, Гаметалар', 'Ички жана сырткы уруктануу, Зиготанын пайда болушу', 'Бластула, Гаструла, Нейрула, Ткандардын бөлүнүшү', 'Түз өрчүү, Метаморфоз аркылуу (кыйыр) өрчүү', 'Мутагендер, Никотин/алкоголь зыяны, Экология'] },
  { id: 3, title: 'Генетика жана өзгөргүчтүк', short: 'Генетика', icon: '⌬', color: 'aqua', topics: ['Генетика илими жана Г. Мендель', 'Мендельдин 1-мыйзамы', 'Мендельдин 2-мыйзамы', 'Дигибриддик аргындаштыруу (Мендельдин 3-мыйзамы)', 'Аллелдик эмес гендердин өз ара таасири', 'Толук эмес доминанттуулук', 'Хромосомалык теория (Т. Морган)', 'Жыныс менен чиркелишкен тукум куучулук', 'Модификациялык өзгөргүчтүк', 'Мутациялык өзгөргүчтүк'], subs: ['Генотип, Фенотип, Доминанттуу жана Рецессивдүү белгилер', 'Моногибриддик аргындаштыруу, Биринчи муундун бирдейлик мыйзамы', 'Белгилердин ажыроо мыйзамы (3:1 катышы)', 'Көз карандысыз тукум куучулук, Пеннет тору (9:3:3:1)', 'Комплементардуулук, Эпистаз, Полимерия', 'Аралык касиеттердин тукум куушу, Анализдөөчү аргындаштыруу', 'Чиркелишкен тукум куучулук, Морганоидалар', 'X жана Y хромосомалар, Дальтонизм жана Гемофилия', 'Тукум куубаган өзгөргүчтүк, Реакция нормасы', 'Гендик, Хромосомалык, Геномдук мутациялар'] },
  { id: 4, title: 'Селекция жана биотехнология', short: 'Селекция', icon: '⌁', color: 'amber', topics: ['Селекция негиздери жана Н.И. Вавилов', 'Өсүмдүк селекциясы', 'Жаныбарлар селекциясы', 'Микроорганизмдер селекциясы', 'Биотехнология жана Гендик инженерия'], subs: ['Түрлөрдүн келип чыгуу борборлору, Сорт жана Порода', 'Инбридинг, Гетерозис, Полиплоидия', 'Тандоо, Аргындаштыруу ыкмалары', 'Антибиотиктер, Ачыткычтар, Штаммдар', 'ГМО, Клондоштуруу, ДНК рекомбинациясы'] },
  { id: 5, title: 'Эволюция жана экология', short: 'Экология', icon: '◌', color: 'coral', topics: ['Ч. Дарвиндин эволюциялык теориясы', 'Жашоо үчүн күрөш', 'Табигый тандоо', 'Популяция — эволюция бирдиги', 'Эволюциянын далилдери', 'Макроэволюция багыттары', 'Антропогенез', 'Экологиялык факторлор', 'Экосистемалар жана Азык тизмеги', 'Биосфера жана В.И. Вернадский'], subs: ['Эволюциялык окуунун келип чыгышы, Табигый тандоо', 'Түр ичиндеги, Түр аралык жана Бейорганикалык чөйрө менен күрөш', 'Кыймылдаткыч, Диэлектрик жана Турукташтыруучу тандоо', 'Популяция генофонду, Мутациялык басым', 'Гомологдук/Аналогдук органдар, Рудименттер жана Атавизмдер', 'Ароморфоз, Идиоадаптация, Жалпы дегенерация', 'Австралопитектер, Архантроптор, Неандерталдар, Кроманьондор', 'Абиотикалык, Биотикалык жана Антропогендик факторлор', 'Продуценттер, Консументтер, Редуценттер, Экологиялык пирамида', 'Жердин тирүү заты, Ноосфера, Заттардын чоң жана кичине айланышы'] }
];

let lessonNumber = 0;
const allLessons = modules.flatMap((module) => module.topics.map((title, index) => ({ id: ++lessonNumber, module, title, sub: module.subs[index] })));
const quizTemplates = [
  { q: 'Бул теманын негизги түшүнүгүн кайсы жооп туура сүрөттөйт?', options: ['Негизги биологиялык процесс жана анын мыйзам ченеми', 'Тек гана химиялык реакция', 'Байкоого тиешеси жок түшүнүк'], answer: 0, why: 'Биологиялык түшүнүктү процесс, түзүлүш жана анын организмдеги ролу менен бирге кароо керек.' },
  { q: 'Түшүнүктү бекемдөөнүн эң туура жолу кайсы?', options: ['Мисалды схема менен байланыштыруү', 'Терминди жаттап гана коюу', 'Маалыматты текшербей кабыл алуу'], answer: 0, why: 'Схема жана турмуштук мисал теорияны эстеп калууга жардам берет.' },
  { q: 'Кайсы ыкма өз алдынча окууга ылайыктуу?', options: ['Салыштыруу таблицасын түзүү', 'Теманы өткөрүп жиберүү', 'Бир гана аталышты окуу'], answer: 0, why: 'Салыштыруу айырмачылыктарды көрүүгө жана себеп-натыйжаны түшүнүүгө шарт түзөт.' }
];

function getLessonContent(lesson) {
  const [a, b, c] = lesson.sub.split(', ');
  return {
    theory: `${lesson.title} темасы организмдин түзүлүшүн, жашоо процессин же жаратылыштагы байланышын түшүндүрөт. Бул бөлүмдө негизги ой — ${a?.toLowerCase() || 'биологиялык процесстер'} түшүнүктөрүн өз ара байланышта кароо. Ар бир организмде түзүлүш менен функция бир бүтүн болот: түзүлүш кандай болсо, анын аткарган кызматы да ошого ылайыкташат.`,
    terms: [a, b, c].filter(Boolean).map((term, index) => ({ term, text: ['Негизги түшүнүк: аныктаманы жана организмдеги ролун эстеңиз.', 'Процесстин жүрүшүн себептен натыйжага карай түшүндүрөт.', 'Практикада бул көрүнүштү мисал же байкоо аркылуу таанууга болот.'][index] })),
    examples: [`${lesson.title} адамдын күнүмдүк жашоосунда да байкалат: тамактануу, кыймылдоо жана айлана-чөйрөгө жооп берүү ушул темага байланыштуу.`, `Мисал катары ${a?.toLowerCase() || 'бул процессти'} алып, анын башталышын, негизги баскычын жана натыйжасын тизип көрүңүз.`],
    flow: ['Баштапкы шарт', 'Негизги процесс', 'Натыйжа', 'Организм үчүн мааниси']
  };
}

export function App() {
  const [dark, setDark] = useState(true);
  const [bookOpen, setBookOpen] = useState(false);
  const [selected, setSelected] = useState(null);
  const [activeModule, setActiveModule] = useState(1);
  const [query, setQuery] = useState('');
  const [done, setDone] = useState(() => JSON.parse(localStorage.getItem('bio-done') || '[]'));
  const [mobileNav, setMobileNav] = useState(false);
  const [quizAnswers, setQuizAnswers] = useState({});

  const filtered = useMemo(() => allLessons.filter((lesson) => `${lesson.title} ${lesson.sub} ${lesson.module.title}`.toLowerCase().includes(query.toLowerCase())), [query]);
  const visibleLessons = query ? filtered : allLessons.filter((lesson) => lesson.module.id === activeModule);
  const content = selected ? getLessonContent(selected) : null;
  const markDone = (id) => { const next = done.includes(id) ? done.filter((item) => item !== id) : [...done, id]; setDone(next); localStorage.setItem('bio-done', JSON.stringify(next)); };
  const downloadPdf = () => { if (!selected) return; const printWindow = window.open('', '_blank', 'width=860,height=720'); if (!printWindow) return; printWindow.document.write(`<html><head><title>BioLab 09 - ${selected.title}</title><style>body{font-family:Arial,sans-serif;max-width:760px;margin:50px auto;color:#17352a;line-height:1.6}h1{color:#087f5b;border-bottom:2px solid #10b981;padding-bottom:15px}h2{color:#087f5b;margin-top:32px}.term{display:inline-block;border:1px solid #10b981;padding:8px;margin:4px;border-radius:4px}small{color:#55766a}</style></head><body><small>BIOLAB 09 / ПАРАГРАФ ${selected.id}</small><h1>${selected.title}</h1><p>${content.theory}</p><h2>Эстеп кал</h2><p>${content.terms.map((item) => `<span class="term"><b>${item.term}</b><br>${item.text}</span>`).join('')}</p><h2>Мисалдар</h2><p>${content.examples.join('<br><br>')}</p><script>window.onload=()=>window.print()</script></body></html>`); printWindow.document.close(); };

  return <div className={dark ? 'app dark' : 'app'}>
    <header className="topbar">
      <button className="brand" onClick={() => { setBookOpen(false); setSelected(null); }}><span className="brand-mark"><Dna size={19} /></span><span><b>BIO</b><em>LAB</em><small>09 / ОКУУ ПЛАТФОРМАСЫ</small></span></button>
      <nav className={mobileNav ? 'nav open' : 'nav'}><button onClick={() => { setBookOpen(false); setSelected(null); }}>Башкы бет</button><button onClick={() => setBookOpen(true)}>Программа</button><button onClick={() => setSelected(allLessons[0])}>Тесттер</button></nav>
      <div className="top-actions"><button className="icon-btn" title="Түстү өзгөртүү" onClick={() => setDark(!dark)}>{dark ? <Sun size={18} /> : <Moon size={18} />}</button><button className="icon-btn menu-btn" onClick={() => setMobileNav(!mobileNav)}>{mobileNav ? <X size={20} /> : <Menu size={20} />}</button><button className="profile">А<small>9-класс</small></button></div>
    </header>

    {!bookOpen && !selected && <main className="hero-page"><div className="hero-copy"><p className="eyebrow"><span></span> 9-КЛАСС · БИОЛОГИЯ</p><h1>Тиричиликти<br /><i>ичинен</i> тааны.</h1><p className="hero-text">Организмдердин сырларын түшүнүү үчүн түзүлгөн заманбап окуу мейкиндиги. 45 тема, визуалдык схемалар жана интерактивдүү тесттер.</p><button className="primary-btn" onClick={() => setBookOpen(true)}>КИТЕПТИ АЧУУ <ChevronRight size={18} /></button><div className="hero-stat"><span><b>05</b><small>модуль</small></span><span><b>45</b><small>параграф</small></span><span><b>{done.length}</b><small>окулду</small></span></div></div><div className="book-stage"><div className="orbit orbit-one"></div><div className="orbit orbit-two"></div><div className="leaf leaf-a">❧</div><div className="leaf leaf-b">❧</div><Dna className="dna-art" size={190} /><div className="book"><div className="book-top">BIOLOGY<br /><strong>09</strong></div><div className="book-line"></div><div className="book-bottom">Тиричиликтин<br />жашыруун тили</div><span className="book-stamp">STUDY<br />EDITION</span></div><div className="book-shadow"></div><div className="floating-note"><Sparkles size={14} /><span>Илим — бул<br /><b>кызыгуу</b> менен башталат.</span></div></div></main>}

    {bookOpen && !selected && <main className="library"><div className="library-head"><div><p className="eyebrow"><span></span> ОКУУ КИТЕПЧЕСИ</p><h2>45 параграф.<br /><i>Бир чоң</i> ачылыш.</h2></div><div className="progress-card"><div className="progress-ring"><b>{Math.round((done.length / 45) * 100)}%</b></div><span>Сиздин прогресс<br /><strong>{done.length} / 45 окулду</strong></span></div></div><div className="search-wrap"><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Термин же тема издөө..." />{query && <button onClick={() => setQuery('')}><X size={16} /></button>}<kbd>⌘ K</kbd></div><div className="library-layout"><aside className="module-list"><p className="aside-label">МОДУЛДАР</p>{modules.map((module) => <button className={activeModule === module.id && !query ? 'module-item active' : 'module-item'} key={module.id} onClick={() => { setActiveModule(module.id); setQuery(''); }}><span className={`module-icon ${module.color}`}>{module.icon}</span><span><b>{String(module.id).padStart(2, '0')}</b> {module.short}<small>{module.topics.length} параграф</small></span><ChevronRight size={16} /></button>)}</aside><section className="lesson-section"><div className="section-head"><span>{query ? `Издөө натыйжасы: ${filtered.length}` : modules[activeModule - 1].title}</span><small>{query ? 'бардык модулдар' : `0${activeModule} / 05`}</small></div><div className="lesson-grid">{visibleLessons.map((lesson) => <button className={done.includes(lesson.id) ? 'lesson-card completed' : 'lesson-card'} key={lesson.id} onClick={() => setSelected(lesson)}><span className="lesson-number">{String(lesson.id).padStart(2, '0')}</span><span className="lesson-info"><b>{lesson.title}</b><small>{lesson.sub}</small></span><span className="lesson-status">{done.includes(lesson.id) ? <Check size={16} /> : <ChevronRight size={17} />}</span></button>)}</div></section></div></main>}

    {selected && <main className="lesson-view"><button className="back-link" onClick={() => setSelected(null)}>← Бардык параграфтарга кайтуу</button><div className="lesson-title"><div><p className="eyebrow"><span></span> {selected.module.short.toUpperCase()} · ПАРАГРАФ {String(selected.id).padStart(2, '0')}</p><h2>{selected.title}</h2><p>{selected.sub}</p></div><div className="lesson-actions"><button className={done.includes(selected.id) ? 'done-btn active' : 'done-btn'} onClick={() => markDone(selected.id)}>{done.includes(selected.id) ? <Check size={17} /> : null} {done.includes(selected.id) ? 'ОКУЛДУ' : 'ОКУЛДУ ДЕП БЕЛГИЛЕ'}</button><button className="icon-btn" title="PDF жүктөө" onClick={downloadPdf}><Download size={18} /></button></div></div><div className="content-grid"><div><section className="content-block theory"><div className="block-title"><span className="block-icon">📌</span><span><small>01 / ТҮШҮНҮК</small><h3>Негизги теория</h3></span></div><p>{content.theory}</p></section><section className="content-block"><div className="block-title"><span className="block-icon">💡</span><span><small>02 / СӨЗДҮК</small><h3>Эстеп кал!</h3></span></div><div className="term-grid">{content.terms.map((item) => <div className="term-card" key={item.term}><strong>{item.term}</strong><p>{item.text}</p></div>)}</div></section><section className="content-block"><div className="block-title"><span className="block-icon">🧪</span><span><small>03 / БАЙЛАНЫШ</small><h3>Мисалдар жана турмушта</h3></span></div>{content.examples.map((example) => <p className="example" key={example}>{example}</p>)}</section></div><aside><section className="content-block flow-block"><div className="block-title"><span className="block-icon">🧬</span><span><small>04 / ВИЗУАЛИЗАЦИЯ</small><h3>Процесстин схемасы</h3></span></div><div className="flow">{content.flow.map((step, index) => <div className="flow-step" key={step}><span>{String(index + 1).padStart(2, '0')}</span><b>{step}</b>{index < content.flow.length - 1 && <i>↓</i>}</div>)}</div></section><Quiz lessonId={selected.id} answers={quizAnswers} setAnswers={setQuizAnswers} /></aside></div></main>}
    <footer><span>© 2025 BIOLAB 09</span><span>Окуу кызыгуудан башталат <Leaf size={14} /></span></footer>
  </div>;
}

function Quiz({ lessonId, answers, setAnswers }) {
  const current = answers[lessonId] || {};
  return <section className="quiz content-block"><div className="block-title"><span className="block-icon">❓</span><span><small>05 / ПРАКТИКА</small><h3>Өзүңдү текшер</h3></span></div><p className="quiz-intro">Ар бир жооптон кийин түшүндүрмөнү окуп, билимиңди бекемде.</p>{quizTemplates.map((item, index) => { const answer = current[index]; return <div className="question" key={item.q}><b>{index + 1}. {item.q}</b><div className="options">{item.options.map((option, optionIndex) => <button className={answer === optionIndex ? (optionIndex === item.answer ? 'option correct' : 'option wrong') : 'option'} onClick={() => setAnswers({ ...answers, [lessonId]: { ...current, [index]: optionIndex } })} key={option}>{option}<span>{answer === optionIndex ? (optionIndex === item.answer ? '✓' : '×') : ''}</span></button>)}</div>{answer !== undefined && <div className={answer === item.answer ? 'feedback correct' : 'feedback wrong'}>{answer === item.answer ? 'Туура!' : 'Ката.'} <span>{item.why}</span></div>}</div>; })}</section>;
}
